### ISSUE TITLE
An open web app to remember what I have lent to whom and when

### ISSUE THREAD

**Issue by Yoric** [Mozilla-Student-Projects/Projects-Tracker#11]
This project is part of the ongoing [Open Web Applications](http://www.mozilla.org/en-US/apps/partners/) effort led by [http://www.mozilla.org](Mozilla) to liberate users from the closed, locked apps and app stores. Open Web Applications bring the power and the freedom of the web to desktops, tablets, cellphones.

Consider the following scenario: Friends borrow my books. I forget which friends. I forget when they borrowed the books. Now if I want my books back, I feel stupid.

Implement a simple [open web application](https://developer.mozilla.org/en-US/docs/Apps) that I can use to record this information.

**Comment by sushant-hiray** [comment]
@Yoric I'm interested in working on this project. I don't have any experience of developing open web applications, but I'll surely love to start off. This does seem to be a good starting option.

**Comment by Yoric** [comment]
Hi @sushant-hiray.
That's great. Unfortunately, at the moment, I am too busy to mentor this.
You can try finding a mentor on our [introduction irc channel](http://client00.chat.mibbit.com/?server=irc.mozilla.org&channel=%23introduction&nick=sushanthiray).

**Comment by nickdesaulniers** [comment]
I'll be happy to help.  You can find me on irc.mozilla.org usually in #openwebapps using the handle `\n`.  Or shoot me an email [first letter of first name][last name] at mozilla dot com.

**Comment by sushant-hiray** [comment]
@nickdesaulniers Thanks a lot :)
@Yoric  I guess @nickdesaulniers  will mentor us. I'll create a repository shortly and post the link here.
I will working on this project along with my friend @gargsanchit31

**Comment by nickdesaulniers** [comment]
@sushant-hiray when you have questions, feel free to mention me in the relevant issues and I'll get an email notification.

**Comment by hvardhanx** [comment]
@nickdesaulniers  We have created this app here : https://github.com/GhostAlgorithm/lendyou
Developers : Jorge Gomez (@GhostAlgorithm) and Harsh Vardhan (@royalharsh)
We would love to get some feedbacks. :)

**Comment by AntoineTurmel** [comment]
@royalharsh It worked great for me !
A plus would be integration with phone contacts.

**Comment by jrg96** [comment]
Where can we get more information about that?

**Comment by jrg96** [comment]
An action that you're performing violates the CSP (content security policy). While this does not affect your app, if you decide to add permissions to your app in the future, you will be unable to do so until this problem is corrected.

What can I do if this violations are from libraries like jQuerym Bootstrap and other third party libraries?

**Comment by jrg96** [comment]
@AntoineTurmel great news I think :D!

https://marketplace.firefox.com/app/lend-you/

And the repo of the project:
https://github.com/InfinioPlus/lendyou-fxos

**Comment by hvardhanx** [comment]
It has also been integrated with phone contacts . :smile:

**Comment by AntoineTurmel** [comment]
@GhostAlgorithm @royalharsh nice job !
I guess the next step could be the ability to sync this list to a remote server :)
