### ISSUE TITLE
Backup SMS OWA

### ISSUE THREAD

**Issue by AntoineTurmel** [Mozilla-Student-Projects/Projects-Tracker#21]
This project is part of the ongoing Open Web Applications effort led by http://www.mozilla.org to liberate users from the closed, locked apps and app stores. Open Web Applications bring the power and the freedom of the web to desktops, tablets, cellphones.

I would like an app to be able to save all my SMS in a file, to make a backup. You can look at Android app to be cross-compatible using XML file.

**Comment by anandsoni11** [comment]
@GeekShadow I would like to contibute to this project. Can you tell me what exactly do we need to do? Also, can you mentor me on this project?

**Comment by AntoineTurmel** [comment]
@anandsoni11 
Sure ! You will need to do a webapp that use access to SMS to make a backup, and allow restoring.
For example you can look at the current SMS app of Firefox OS:
https://github.com/mozilla-b2g/gaia/tree/master/apps/sms

An use case would be:
- Export SMS from Android on a .xml file
- Import this xml file on Firefox OS

You will need to write all values in the matching database.

You can also find more documentation here:
https://developer.mozilla.org/en-US/docs/WebAPI/WebSMS

**Comment by anandsoni11** [comment]
@GeekShadow please guide me on how to begin. What environment do I need to set up and what tools/API's that I need to know?

**Comment by AntoineTurmel** [comment]
@anandsoni11 
You need text editor to edit HTML/CSS/JavaScript (like vim, geany, notepad++).
You can get templates for your app here: https://github.com/mozilla/mortar
For tools you can use Firefox OS Simulator which is an add-on installable here: https://addons.mozilla.org/fr/firefox/addon/firefox-os-simulator/ also Firefox have some very good developers tools built-in.
For API you should look on how WebSMS work (I posted link in my previous comment).

**Comment by AntoineTurmel** [comment]
@anandsoni11 are you still ok to work on this project ?

**Comment by hansgogia** [comment]
@GeekShadow is this still alive?

**Comment by AntoineTurmel** [comment]
@hansg01 hmm the project is still open yup

**Comment by hansgogia** [comment]
@GeekShadow Alright, I have read the pre requisites above and shall be working on this. Anything else I need to know?

**Comment by hansgogia** [comment]
@GeekShadow Alright then. i have read the pre requisites mentioned above and will be contributing on this project. Is there anything else I need to know?

**Comment by AntoineTurmel** [comment]
No you can go on :)

**Comment by brianeshaw** [comment]
Hey everyone, has there been any progress on this project? This is exactly what I've been looking for and there doesn't appear to be anything else available to do the task of transferring old texts (or backing them up) to or from Firefox OS.

**Comment by AntoineTurmel** [comment]
@PerturbedPenguin 
No progress from what I can see. Feel free to contact to ask here for help.

**Comment by reznord** [comment]
@AntoineTurmel  I guess there are already some apps for Android which can do this. If we can get those apps, we can port them to use in Firefox OS right?

This is just an idea from my side. But need to discuss more about the app. In Android for example there is Super Backup[1](https://play.google.com/store/apps/details?id=com.idea.backup.smscontacts&hl=en) app for Android which does the same thing exactly.

**Comment by Amanjot1507** [comment]
Hi!
I would like to work on this project. Is it up for grabs?

**Comment by AntoineTurmel** [comment]
@Amanjot1507 yes !!!!

@Anup-Allamsetty 
You can't really port easily the Android app because you have to use WebSMS API. But you can use the same XML output format or also JSON :)

**Comment by Amanjot1507** [comment]
Nice!
I am going to start on this now.
I read your comments on getting started, but still I would need help.
Will you mentor this project?

**Comment by AntoineTurmel** [comment]
@Amanjot1507 I would be pleased yes !
as I said earlier, look at the SMS application and WebSMS API.
I'm for a XML and/or JSON import/export

**Comment by hansgogia** [comment]
Hey guys
I had started this project as my minor project last year but I had to hold back because of unavailability of a firefox device. I ran the Open WebApp on emulator but couldn't figure out how to add messages on it to test. All I could get was point to null object.

**Comment by Amanjot1507** [comment]
@AntoineTurmel 
Hey!
Anywhere else I could contact you? Email, IRC etc. ?
Have a lot of questions to ask, if you don't mind.

**Comment by AntoineTurmel** [comment]
@Amanjot1507 
on IRC: irc.mozilla.org
my nick is GeekShadow
mail: antoine [dot] code [at] turmel [dot] info

**Comment by Amanjot1507** [comment]
@AntoineTurmel 
1. Is it possible to have SMS messages already in the firefox OS simulator, so that I can test their import/export after I have created the app?
2. SMSs should be backed up as an XML document when exported and imported by parsing the XML document. Is that correct or is some other implementation required?
3. Do I have to create a standalone web app or is it supposed to be embedded in the form of an option in the pre-existing SMS app?

Also, could you please assign this project to me?

**Comment by AntoineTurmel** [comment]
1. Hmm I'm looking at this, it should be possible to "dogfood" to preload with SMS
2. It is correct, if you choose XML format you should use the same format this Android app use :
   https://play.google.com/store/apps/details?id=com.riteshsahu.SMSBackupRestore&hl=fr (so people can migrate easily).
   A JSON import/export would be a plus, but not required.
3. To begin with, a standalone app is good. If your app works fine I think you could try to integrate it on the pre-existing SMS app. See [Bug 1056836](https://bugzilla.mozilla.org/show_bug.cgi?id=1056836).

Assignation:
I can't do that on the GitHub project because I don't have enough rights and the owner should be in holidays right now.
But consider yourself as assigned on it :)

**Comment by AntoineTurmel** [comment]
Also you can look at @frayar work here:
https://github.com/frayar/SMSBackupRestore

**Comment by reznord** [comment]
@AntoineTurmel 
Is the above comments are mentioned to me or is it to Amanjot? Asking about the bug assigning. I have already started working on this.

**Comment by AntoineTurmel** [comment]
@Anup-Allamsetty it's for everyone working on this project.
Please work together then :)

**Comment by reznord** [comment]
@AntoineTurmel @anandsoni11 @hansg01 @Amanjot1507 
Hi, If anyone is working on this project, I would be happy to join to work together on this project. I don't have anyone's contacts. If anyone is working on this project, please feel free to contact me at allamsetty.anup@gmail.com

**Comment by Waterloo** [comment]
@AntoineTurmel  I am interested in taking this project, but i don't think that a packaged app can query the messages...

**Comment by Amanjot1507** [comment]
@Waterloo 
I built a packaged app for this. I succesfully queried the SMS database and stored the messages in a file.
The main problem is the addition of these stored messages back to the SMS database (the Restore functionality). The Core API does not have any function to add messages to the SMS database.

@AntoineTurmel could help further.

**Comment by AntoineTurmel** [comment]
Yeah unfortunately, it's not possible yet to restore SMS, but Mozilla is working on a new feature called "add-ons" for apps. It will let you add features to current apps.
https://bugzilla.mozilla.org/show_bug.cgi?id=1162200

@Amanjot1507 you did a very great job so far with the export feature I wish I could have been more available to help you.

**Comment by Waterloo** [comment]
Thats a great thing. I was in search for an app like that. where can i find the source of the current build ?

**Comment by Amanjot1507** [comment]
@AntoineTurmel Without you I would still have been struggling with running gaia. :P

if you're relatively free now, could you guide me in adding the restore functionality to the main codebase ?

**Comment by AntoineTurmel** [comment]
Closing this issue since Firefox OS is discontinued 😢
