### ISSUE TITLE
Improve Rust's integration with C code

### ISSUE THREAD

**Issue by brson** [Mozilla-Student-Projects/Projects-Tracker#26]
Rust has an out-of-tree tool called [bindgen](https://github.com/crabtw/rust-bindgen), used for automatically generating Rust bindings to C code. It is very useful, but could be integrated better with Rust. In particular, there should be ways for the Rust compiler to automatically generate C bindings.

See also: [2124](https://github.com/mozilla/rust/issues/2124), [1862](https://github.com/mozilla/rust/issues/1862), [2045](https://github.com/mozilla/rust/issues/2045), [2805](https://github.com/mozilla/rust/issues/2805), [2373](https://github.com/mozilla/rust/issues/2373)

**Comment by akshayratan** [comment]
What's the status of this project ?

**Comment by brson** [comment]
The ultimate goal of this project - to automatically create and build Rust bindings to C code using clang - is still not completed, but also the need for such a tool has not been pressing.

I imagine there is still some desire in the Rust community to pull clang and bindgen into the main repo _eventually_. There are a few factors that make me think it's no longer the right time to do this project: distributing clang is a big change, and we are in the middle of stabilizing Rust for its first major release; merging a big codebase like clang into another big codebase like Rust is politically difficult, and we would need to get broad community buy-in _before_ starting the project.

Most of the Rust projects in this bug tracker are out of date. You may have better luck finding Rust projects on the main Rust issue tracker - the "interesting-project" tag.

**Comment by brson** [comment]
Closing because I think this is no longer a great choice for students wanting to get involved with Rust.
