### ISSUE TITLE
Create a Rust source code browser

### ISSUE THREAD

**Issue by brson** [Mozilla-Student-Projects/Projects-Tracker#29]
Create a tool that uses the `rustc` and `rustdoc` libraries to present an annotated source code browser, with hyperlinks, type annotations, etc. Possibly get inspiration from mozilla-central's MXR tool.

See also: [3485](https://github.com/mozilla/rust/issues/3485)

**Comment by jdm** [comment]
More interesting for inspiration would be http://dxr.allizom.org/, I think.

**Comment by Lingelo** [comment]
HI, 
I am a french student. My university is based in Evry (France). Currently, I am looking for a topic for my R&D project and I would like to participate to this issue. 
How can I contact you ? 

Kind regards

**Comment by brson** [comment]
@GeminiCode The best way to communicate about this issue is through the corresponding page on the rust issue tracker: https://github.com/mozilla/rust/issues/3485, or alternately through the rust-dev mailing list (if you want to get the opinion of a wider audience.

If you need to talk in private then feel free to email me (banderson@mozilla.com).

**Comment by brson** [comment]
@nikomatsakis will be interested in discussing plans on this subject

**Comment by brson** [comment]
Closing as obsolete as Rust works with MXR now.
