### ISSUE TITLE
Create rustfmt tool, ala gofmt

### ISSUE THREAD

**Issue by brson** [Mozilla-Student-Projects/Projects-Tracker#30]
Being opinionated and strict about syntax is becoming popular, and the Go community has a culture of formatting all their code the same with `gofmt`. Rust has a pretty printer built into the compiler, but it doesn't always produce the best output, isn't 100% reliable, and isn't wired up to an end-user tool.

This will involve creating a command line interface to the pretty printer and fixing pretty-printer deficiencies. The pretty printer is notoriously difficult to control in some cases and is not passionately maintained, so it may be profitable to do a refactor and/or rewrite. Investigating how `gofmt` is structured could be helpful.

See also: [3195](https://github.com/mozilla/rust/issues/3195)

**Comment by icholy** [comment]
:+1: gofmt is great

**Comment by brson** [comment]
Closing. Graydon is going to be working on this personally.
