### ISSUE TITLE
Port Rust to ARM

### ISSUE THREAD

**Issue by brson** [Mozilla-Student-Projects/Projects-Tracker#34]
Although a full ARM port that passes all regression tests is a big project, any progress on porting Rust to ARM would be well received.

See also: [1858](https://github.com/mozilla/rust/issues/1858)

**Comment by kud1ing** [comment]
There is a pull request für Rust Android cross compilation which contains a significant portion of ARM code: https://github.com/mozilla/rust/pull/4343

**Comment by brson** [comment]
Essentially done.
