### ISSUE TITLE
Create a Rust actor library

### ISSUE THREAD

**Issue by brson** [Mozilla-Student-Projects/Projects-Tracker#36]
Rust has a lot of powerful concurrency tools, but they aren't packaged up into a high-level, consistent interface.

Things that would be great in an actor library:
- High-level help with implementing actor patterns, nice interface, minimal boilerplate
- Cross-process actors with sandboxing. Sandboxing is very important to [Servo](http://github.com/mozilla/servo), which has some initial sandboxing libraries.
- Network-based messaging and actors
- Reliable failure and recovery schemes. Rust has linked task failure, but no higher-level constructs to help users make use of it for creating reliable systems ala Erlang OTP.

Take inspiration from Scala, Akka and Erlang.

See also: [3573](https://github.com/mozilla/rust/issues/3573)

**Comment by donbrowne** [comment]
Hi there, I'd be interested in working on this project as part of a dissertation, should I drop you (and/or anyone else) a mail about this?

**Comment by brson** [comment]
I don't think that now is the time for this project. There's too much churn going on in the Rust runtime and there are going to be several interns working on Rust concurrency issues through the summer.

**Comment by ysangkok** [comment]
@brson Do you think the Rust runtime is stable enough now?

**Comment by Yoric** [comment]
Actually, there are now several actor libraries for Rust, so I'd keep this issue closed.

**Comment by ysangkok** [comment]
@Yoric are you talking about these two?
- https://github.com/kolloch/actors
- https://github.com/mnussbaum/washed_up

**Comment by Yoric** [comment]
Yes, these two and https://github.com/jonathandturner/actress
