### ISSUE TITLE
Implement big integers for Rust

### ISSUE THREAD

**Issue by brson** [Mozilla-Student-Projects/Projects-Tracker#37]
Rust has always planned for, but never implemented, a big integer type. This is pretty straightforward and self-contained, just writing and testing a complete feature from scratch.

See also: [33](https://github.com/mozilla/rust/issues/33)

**Comment by kud1ing** [comment]
Probably fixed in https://github.com/mozilla/rust/pull/4198

**Comment by kud1ing** [comment]
Can this be closed since #4198 was merged?
Further work could be supported by following issues.

**Comment by Yoric** [comment]
Closing.
