### ISSUE TITLE
Miscellaneous Rust projects

### ISSUE THREAD

**Issue by brson** [Mozilla-Student-Projects/Projects-Tracker#38]
Here are more ideas I pulled out of the Rust issue tracker.
- Add compiler-inserted yield checks - task scheduling is totally unfair, and part of the problem is that tasks don't yield automatically yet unless they are using library functions that must yield for correctness. https://github.com/mozilla/rust/issues/524
- Add static crate linking - there is some bitrotted code for this already. https://github.com/mozilla/rust/issues/552
- Add a 1:1 task:thread scheduling mode, collect some performance numbers. https://github.com/mozilla/rust/issues/595
- Add config files, build-generated lists of attributes that are merged into the crate attributes. https://github.com/mozilla/rust/issues/612
- Fix debug info. Rust code can't really be debugged in gdb because it doesn't emit the proper DWARF info. This is mostly about applying the LLVM APIs correctly, but will involve low-level debugging. Fun stuff.
- Get gcov working (code coverage). Probably depends on the above. https://github.com/mozilla/rust/issues/690
- Add a task monitor. This would probably be a named service that can be queried for the task state, can provide messages on task lifecycle events. Also give tasks useful names.
- Write or finish a pygments lexer, upstream it, and get github to use it to syntax highlight Rust code. https://github.com/mozilla/rust/issues/1198
- Improve cargo, Rust's package manager. This is an open-ended problem, as we don't have a firm design in mind.
- Improve rustdoc, Rust's documentation generator. As above, the tool exists, but isn't great.
- Add command-line configuration of runtime environment. https://github.com/mozilla/rust/issues/1497
- Improve the formal rust grammar and make it testable. https://github.com/mozilla/rust/issues/2234

**Comment by sanxiyn** [comment]
1198 is done now. cargo is now rustpkg.

**Comment by brson** [comment]
Closing this grab-bag of old stuff.
