### ISSUE TITLE
Minimalistic web development environment for FirefoxOS

### ISSUE THREAD

**Issue by Yoric** [Mozilla-Student-Projects/Projects-Tracker#43]
A cellphone is certainly not the best host environment to develop web pages. Chances are that, for the foreseeable future, nobody will develop the next Google Docs without using a keyboard.

However, with imagination, we can certainly do something. The objective of this project is to explore the user interface of a minimalistic environment that could be used to:
- quickly draw simple webpages using the touchscreen;
- give properties to user interface elements;
- attach JavaScript code to events;
- deploy the result as an installable web application.

The inspiration for this environment is the long defunct [HyperCard](http://en.wikipedia.org/wiki/Hypercard) project.

**Comment by imjacobclark** [comment]
Hi, I'd like to take this, is that possible?

**Comment by Yoric** [comment]
As it turns out, [AppMaker](https://github.com/mozilla/appmaker) has done most of what we wanted to do with this project.
If you are interested in this project, you should get in touch with the developers of AppMaker and help them out.
