### ISSUE TITLE
Podcast app

### ISSUE THREAD

**Issue by etiennesegonzac** [Mozilla-Student-Projects/Projects-Tracker#46]
This project is part of the ongoing Open Web Applications effort led by http://www.mozilla.org to liberate users from the closed, locked apps and app stores. Open Web Applications bring the power and the freedom of the web to desktops, tablets, cellphones.

An open web app implementing a simple podcast player.
- Managing a list of subscriptions (RSS feeds)
- Support for episodes' states (new, listened...) (an indexedDB back-end would make sens)
- Streaming each episode with an `<audio>` player
- Caching episodes for offline use with the [Device Storage API](https://wiki.mozilla.org/WebAPI/DeviceStorageAPI)

Probably a fair amount of code to share with the RSS Reader #8 project.

**Comment by AntoineTurmel** [comment]
+1 We would love this to integrate with Nightingale project :)

**Comment by AntoineTurmel** [comment]
A repo working on this :
https://github.com/mozilla/high-fidelity

**Comment by Asherehsa** [comment]
This looks super cool, I'd also like to see it work with the Gpodder API http://wiki.gpodder.org/wiki/Web_Services/API_2

**Comment by AntoineTurmel** [comment]
Closing this, since Mozilla work on it, feel free to help on https://github.com/mozilla/high-fidelity open issues.
