### ISSUE TITLE
Port Firefox mobile Reader mode to Gaia's browser app

### ISSUE THREAD

**Issue by etiennesegonzac** [Mozilla-Student-Projects/Projects-Tracker#47]
More infos on the reader mode: http://lucasr.org/2012/09/03/reader-mode-in-firefox-beta-for-android/
Source for the gaia browser app: https://github.com/mozilla-b2g/gaia/tree/master/apps/browser

**Comment by AntoineTurmel** [comment]
Closing it for now as Firefox OS is discontinued...
