### ISSUE TITLE
Port DOSBox to the web

### ISSUE THREAD

**Issue by Yoric** [Mozilla-Student-Projects/Projects-Tracker#49]
[DOSBox](http://www.dosbox.com) is an open-source emulator used to run old PC games on just about any recent platform. The objective of this project is to attempt to port DOSBox to make it able to run on the web.

As DOSBox is written in C++, it should be possible to port it semi-automatically using [Emscripten](https://github.com/kripken/emscripten). This will, however, require considerable work.

**Comment by souravsingh** [comment]
Here is the repository for the project:https://github.com/souravsingh/dosbox-port.git

**Comment by Yoric** [comment]
Assigned to @souravsingh

**Comment by ngsankha** [comment]
There is an Emscripten port of DOSBox than can be found here: https://github.com/dreamlayers/em-dosbox/

**Comment by Yoric** [comment]
Closing this project, then.
