### ISSUE TITLE
Add ownCloud support for Thunderbird Filelink feature

### ISSUE THREAD

**Issue by AntoineTurmel** [Mozilla-Student-Projects/Projects-Tracker#55]
More information here:

https://bugzilla.mozilla.org/show_bug.cgi?id=770256
https://github.com/owncloud/core/issues/699
http://bugs.owncloud.org/thebuggenie/owncloud/issues/oc-1598

Short:
Thunderbird allow upload of big files on web services like YouSendIt and Dropbox. It would great to be able to upload files on your own server using ownCloud.

**Comment by alefattorini** [comment]
Sorry but using "webdav for filelink" addon i can configure webdav repository of owncloud,
But something is wrong.. when TB try to insert the link i have this error:
"Unable to upload LJxxxx.epub to WebDAV"
Any help? Could be an useful feature!!

**Comment by AchoArnold** [comment]
This project looks interesting and I may like to work on it this summer. Please who can I contact If I need more information about the project

**Comment by AntoineTurmel** [comment]
Done
https://addons.mozilla.org/en-US/thunderbird/addon/owncloud-for-filelink/
