### ISSUE TITLE
File transfer open web application (ftp client)

### ISSUE THREAD

**Issue by Yoric** [Mozilla-Student-Projects/Projects-Tracker#58]
The objective of this project is to implement an open web application implementing the [FTP](en.wikipedia.org/wiki/FTP) protocol.

**Comment by AntoineTurmel** [comment]
+1 with also sftp

**Comment by sadouanouan** [comment]
Bonjour, pourrait-on avoir un peu des détails sur ce projet. C'est un projet qui m’intéresse.

**Comment by Yoric** [comment]
Malheureusement, pour pouvoir démarrer ce projet, il va falloir attendre que la fonctionnalité [TCPSocket](https://developer.mozilla.org/en-US/docs/DOM/TCPSocket) soit disponible pour toutes les applications. Je vais enlever ce projet de la liste pour le moment.

**Comment by sadouanouan** [comment]
ok

**Comment by AntoineTurmel** [comment]
Rien n'empêche la création d'une application privilégiée pour le moment. (Ça devra aussi être le cas pour la création d'une application de client SSH).

**Comment by rabimba** [comment]
I would like to take this one up @AntoineTurmel

**Comment by AntoineTurmel** [comment]
@rabimba feel free to do it :)

This have already been done but not open sourced:
https://marketplace.firefox.com/app/izzyftp

**Comment by AntoineTurmel** [comment]
Nevermind it's open sourced : https://github.com/izzyway/izzyftp
You can contribute on this repository, I'm closing this issue :)
