### ISSUE TITLE
An open web app for reading barcodes

### ISSUE THREAD

**Issue by lissyx** [Mozilla-Student-Projects/Projects-Tracker#6]
This project is part of the ongoing [Open Web Applications](http://www.mozilla.org/en-US/apps/partners/) effort led by [http://www.mozilla.org](Mozilla) to liberate users from the closed, locked apps and app stores. Open Web Applications bring the power and the freedom of the web to desktops, tablets, cellphones.

The objective of this project is to implement an [open web application](https://developer.mozilla.org/en-US/docs/Apps) that can read [QR codes](http://en.wikipedia.org/wiki/QR_code).

Features:
- take a picture with your cellphone/tablet/webcam;
- recognize any QR code on the picture;
- display the result;
- if the result is an URL, offer the ability to follow that link.

**Comment by lissyx** [comment]
An application that could read QR Codes and any other kind of barcode (1D, 2D) could be very useful, especially in the context of Boot2Gecko/FirefoxOS.

Features :
- Scanning 1D/2D barcode using the camera
- Extracting content
- Interacting with the user (e.g., if it's an URL open it, etc.)
- Provide MozActivity to allow other application to use barcode reading features

**Comment by gasolin** [comment]
I got similar idea and like to elaborate more on this topic.
Since QRCode is the tech that need no extra hardware support. It's a good fit and we can deeply integrate it in Firefox OS. 

For example:
- scan QRCode to auto-configure wifi settings
- scan QRCode to redirect user to MarketPlace

And I believe once we have NFC support, we can reuse these infrastructures, too.

**Comment by gasolin** [comment]
Have a workable barcode scanner http://gasolin.github.io/qrcode_scanner/
http://www.youtube.com/watch?v=F-bqH-0tYnk

project source
https://github.com/gasolin/qrcode_scanner/

welcome to contribute!

**Comment by reznord** [comment]
Hi,

This project sounds interesting to me. Can I get assigned to this project? Can I get more information about this?

**Comment by AntoineTurmel** [comment]
@lissyx @Anup-Allamsetty 
I assume there are enough QR/Barcode reader on the marketplace so this issue can be closed ?
Maybe the bug could be renamed as to include QR Code reading in the Gaia Camera app ?
