### ISSUE TITLE
An application to search for Mozilla student projects, mentored bugs, etc.

### ISSUE THREAD

**Issue by Yoric** [Mozilla-Student-Projects/Projects-Tracker#63]
We currently have a system to search for [mentored bugs](http://www.joshmatthews.net/bugsahoy/) and another system to search for [student projects](https://github.com/Yoric/Mozilla-Student-Projects/issues). The objective of this project is to build a new application, possibly based on @jdm's [Bugs Ahoy!](http://www.joshmatthews.net/bugsahoy/) that will unify both, by letting users search on different sources at once, with various criteria.

If successful, this application will be used by several generations of students and contributors!

If you are interested, please contact @jdm or @Yoric.

**Comment by jdm** [comment]
Bugs Ahoy already has the ability to grab issues from Github projects. The more complicated part would be figuring out how to categorize these student project so they show up with related mentored bugs.

**Comment by jamornsriwasansak** [comment]
I'm interest in this project but may I ask you a question?
How long duration of project?

**Comment by jdm** [comment]
I'm not convinced that this is a very useful project idea right now.

**Comment by Yoric** [comment]
In that case, let's close this project.
