### ISSUE TITLE
Multi-profile Firefox

### ISSUE THREAD

**Issue by Yoric** [Mozilla-Student-Projects/Projects-Tracker#72]
Firefox has a hidden feature that lets a user manage several profiles in different windows (a profile has its own identity, add-ons, cookies, history, etc.). However, there is no menu or button to handle this.

The objective of this project is to develop a Firefox add-on to make this feature available for users.

**Comment by lpy** [comment]
Seems interesting. Could you please provide more information to help me start this? I am willing to have a try.

**Comment by Yoric** [comment]
At the moment, launching Firefox from the command line with options `firefox --no-remote --ProfileManager` opens a new Firefox with the profile dialog which lets users choose a profile (it might be `firefox /no-remote /ProfileManager` under Windows, I haven't checked). Similarly, `firefox --no-remote -P path/to/the/profile/dir` opens a new Firefox with the given profile.

That's not ideal, because:
- it's hidden;
- the `--no-remote` argument means that you can launch several independent windows with the same profile, which can cause bugs;
- the dialog is kind of ugly.

The objective of this project is to provide the feature in a nicer way. I believe that this should be a nice UI that still calls the command-line behind the scene, but there may be alternatives.

**Comment by Mte90** [comment]
There is this extension for firefox for open a new window of firefox with a different profile https://addons.mozilla.org/en-US/firefox/addon/profileswitcher/

**Comment by Yoric** [comment]
Good point, @Mte90. I guess this project becomes "See if  https://addons.mozilla.org/en-US/firefox/addon/profileswitcher/ can be improved, improve it if possible."

**Comment by klgrooms** [comment]
I would be interested in trying to improve this as an add-on if still desired.

**Comment by AntoineTurmel** [comment]
see also https://addons.mozilla.org/fr/firefox/addon/profilist/?src=api https://github.com/Noitidart/Profilist which is pretty nice @Yoric

**Comment by Mte90** [comment]
now there is about:profiles so i think that we can close this ticket

**Comment by AntoineTurmel** [comment]
@Mte90 it's nice but not discoverable really for a basic user

**Comment by Mte90** [comment]
there are many extension that simplify that already shared on the ticket for that reason i think that can be closed

**Comment by AntoineTurmel** [comment]
Right :)
