### ISSUE TITLE
Guitar tuning tool

### ISSUE THREAD

**Issue by Yoric** [Mozilla-Student-Projects/Projects-Tracker#73]
It would be useful for guitar players to have a tool that can help them tune their instrument:
- [play the expected frequency](https://developer.mozilla.org/en-US/docs/Web_Audio_API) for each string so that guitar players can tune by ear (easy);
- [perform sound recognition](https://developer.mozilla.org/en-US/docs/Web/API/Navigator.getUserMedia) using the microphone on the sound played by the guitar player, to display the difference of frequency between the expected frequency and the actual sound played.

**Comment by arasbm** [comment]
Hi Yoric, this sounds very interesting to me and I would love to make a good and usable tuner for FirefoxOS. I use [PitchLab tuner](https://play.google.com/store/apps/details?id=com.symbolic.pitchlab) on my android devices and it is by far one of the best tuner apps I have used. Perhaps we can get some inspiration from that and other well received tuner apps out there.

I am an intermediate js developer and I have already published a couple of very simple and small apps on Firefox Marketplace. I can dedicate around 5 to 10 hours a week to this. Do you think that would be enough to kickstart it? Can you tell me more about the process. Would I be able to get any help/menthorship on this?

In case anyone else is also interested in this as well -- I am very easy going and would love to work with others.

**Comment by Yoric** [comment]
Sounds good. I'll be one of the first users of the tool :)

I believe that the main difficulties you will encounter will be with generating (not too difficult), capturing (not too difficult) and treating sound (harder). I'll ask someone who knows these APIs well to serve as mentor.

**Comment by padenot** [comment]
I can mentor this if needed, feel free to ask questions.

**Comment by arasbm** [comment]
Thank you Paul, that would be great!
I will create a base repo in the next couple of days and will link here. Just wondering right now, do you know what version of FirefoxOS we will be targeting? I think the last time I checked `getUserMedia` was not yet supported in FirefoxOS, but I believe it has been added to a recent version, I just don’t know which one.

**Comment by padenot** [comment]
Aras, you need getUserMedia + Web Audio for that. I'd recommend you to get a gecko master to experiment.

**Comment by arasbm** [comment]
Here is the skeleton repository: https://github.com/arasbm/tuning-fox

It does not do anything yet. I put a couple of small modules in it for saving settings and detecting gestures for later use, and the icon is a placeholder for now. I will checkout gecko master in the next few days and try to get that rolling (I have not done that before so it may take a bit longer). Please watch that repo, and any comment or suggestions let me know. Thanks!

**Comment by Mte90** [comment]
http://www.freetuner.co/
Add a manifest for this?

**Comment by Mte90** [comment]
https://marketplace.firefox.com/app/afinador-para-ukelele?src=search
https://marketplace.firefox.com/app/free-guitar-tuner-1?src=search
https://marketplace.firefox.com/app/firechord?src=search

Maybe this ticket is to be closed
