### ISSUE TITLE
Flappy bird for firefox OS

### ISSUE THREAD

**Issue by TeliHub** [Mozilla-Student-Projects/Projects-Tracker#76]
Hello,

We are students from Evry :dancer: in Master degree.

We'd like to develop this great game for firefox OS : Flappy bird.
This game is a revolution, already available through the play store or the App store.
I work with @KvnOnWeb

Thank you to confirm that the subject is accepted.
Cheers,
Téli

**Comment by TeliHub** [comment]
http://androidcommunity.com/flappy-bird-enters-play-store-as-latest-casual-gaming-addiction-20140202/

**Comment by Yoric** [comment]
Are you the authors of Flappy Bird for Android?
If not, and if you want to work on this, you **need** to get the written authorization of the authors of Flappy Bird. Without this, cloning their game would be illegal.

**Comment by TeliHub** [comment]
We are not the authors of Flappy Bird for Android,

As a result, we'll work on a Flappy Bird like. 

The game's goal will be about the same but we'll do it our way and customized by ourselves.
Thank you

**Comment by AntoineTurmel** [comment]
@TeliHub 
"This game is a revolution", it's just a frustrating game x)

**Comment by AntoineTurmel** [comment]
It has already been done in HTML5:
https://marketplace.firefox.com/app/flappy-birds
