### ISSUE TITLE
SSH and Terminal Client

### ISSUE THREAD

**Issue by AntoineTurmel** [Mozilla-Student-Projects/Projects-Tracker#80]
It would be super nice to have a SSH Client on Firefox OS using [TCPSocket](https://developer.mozilla.org/en-US/docs/Web/API/TCPSocket).

See [Bug 878972](https://bugzilla.mozilla.org/show_bug.cgi?id=878972) and [this etherpad](https://etherpad.mozilla.org/UiQA0T4Xer).

**Comment by Chinmay26** [comment]
hi @AntoineTurmel  @Yoric ,
I would love to start working on this. The anyterm solution proposed here[0] and the webshell solution [1] are not the proper fixes, am i right??
I will start digging more into this. Can someone suggest the next steps?

[0]https://support.mozilla.org/de/questions/1006954
[1]http://piie.net/index.php?section=firefoxos

**Comment by AntoineTurmel** [comment]
Anyterm and webshell are just workaround and are not really that reliable.
I think you should look on how FireSSH works and how you could port it with JavaScript and TCPSocket.
You can grab Firefox Nightly and try WebIDE to make a sample WebApp.

**Comment by AntoineTurmel** [comment]
So the project is under work:
https://github.com/chuckwagoncomputing/fxos-firemote (Firefox OS client)
https://github.com/chuckwagoncomputing/paramikojs (JS Library ported for Gaia)

If you want to help @Chinmay26 ;)

**Comment by Chinmay26** [comment]
Thanks for the ping @AntoineTurmel . I will have a look around .

**Comment by rabimba** [comment]
@AntoineTurmel I think I wrote a Telnet client long ago which is available in FxOS https://marketplace.firefox.com/app/fire-telnet?src=search

It won't be hard to implement SSH over it. 

PS: Oh and I remember author of firemote getting in touch with me early January when I was travelling...

**Comment by AntoineTurmel** [comment]
@rabimba good :) Feel free to contribute with @chuckwagoncomputing on it !

**Comment by AntoineTurmel** [comment]
Closing this issue since it's in work by @chuckwagoncomputing
