### ISSUE TITLE
Write SMS from desktop to be send on Firefox OS

### ISSUE THREAD

**Issue by AntoineTurmel** [Mozilla-Student-Projects/Projects-Tracker#82]
The idea comes from [Airdroid](https://www.airdroid.com/).
It would be nice to have an app to write text messages from a desktop computer and send them to Firefox OS.

**Comment by Yoric** [comment]
So, this would require patching the Gaia SMS app to make it able to receive messages that are not SMS, right?

**Comment by AntoineTurmel** [comment]
Either patching Gaia SMS or forking it...

**Comment by Givemore** [comment]
can you please elaborate more of what do you want to do exactly because i am finding it difficult to understand

**Comment by AntoineTurmel** [comment]
@Givemore 
1. connect my computer to my phone
2. I have a web page or app on my computer with a text box to type my SMS and list to choose my contact
3. I hit send button
4. The message is sent to phone and SMS is sent

**Comment by Givemore** [comment]
Cool i that wont be a problem and i have once done something like that before. So my problem is i do not have any firefox os device that i can use to implement that on... normally i use firefox os simulators for my app development. So when do you want it done?

**Comment by AntoineTurmel** [comment]
There is no planning date, you can do it when you can ;)
A Firefox OS device is needed because you can't use SMS API on the Simulator unfortunately.

**Comment by Givemore** [comment]
I really wanted to do that... hope i will find the next interesting project

**Comment by AntoineTurmel** [comment]
Maybe @Amanjot1507 you are interested ?
You have to display SMS of the phone on the desktop and a box to allow send an SMS.

You can take inspiration from [oCSMS](https://apps.owncloud.com/content/show.php/ownCloud+SMS?content=167289) and [AirDroid](https://www.airdroid.com/).

You could also use the Push API :)

**Comment by Amanjot1507** [comment]
Yeah, I am!

I'm reading it up, I'll ping you if I have any questions. :)

**Comment by AntoineTurmel** [comment]
You will also need the Contact API to get username/phone match.

**Comment by AntoineTurmel** [comment]
Closing it for now as Firefox OS is discontinued...
