### ISSUE TITLE
Remote notifications of Firefox OS

### ISSUE THREAD

**Issue by AntoineTurmel** [Mozilla-Student-Projects/Projects-Tracker#83]
It would be nice to be able to display Firefox OS device notifications on a computer: call, sms etc.

Just like [Android notifier](https://code.google.com/p/android-notifier/).

**Comment by Mte90** [comment]
Missing an api for read the notifications on Firefox OS :-/

**Comment by AntoineTurmel** [comment]
Ok so it would need to be an App add-on or a gaia modification.
(Apps add-ons are coming see : https://bugzilla.mozilla.org/show_bug.cgi?id=923897)

**Comment by AshishKhatkar** [comment]
Hello There!

I and some of my friends would like to work on a modification that will present an API for other applications to read the notifications in Firefox OS. Such an API can be used by apps like AirDroid or other file functions apps that need access to the notifications generated by Firefox OS. It can also be used to monitor events on the Phone by, say, a desktop application.

Please let me know if this project would be worth it, and if any one of you would be willing to mentor this project. :D

**Comment by AntoineTurmel** [comment]
@AshishKhatkar you can go for it :+1:

**Comment by AshishKhatkar** [comment]
@AntoineTurmel will you be mentoring us or we have to find someone.

**Comment by devs4v** [comment]
Hello @AntoineTurmel,
I am in with @AshishKhatkar for this project. We would like to have some guidance as to what all we should start concentrating on to successfully develop this project. Any leads or focus areas we should have a look?

**Comment by AntoineTurmel** [comment]
Closing it for now as Firefox OS is discontinued...
