### ISSUE TITLE
Migration assistant

### ISSUE THREAD

**Issue by AntoineTurmel** [Mozilla-Student-Projects/Projects-Tracker#88]
The idea is to build an app to help user move from Android, Windows Phone or iPhone to Firefox OS. (Even from Firefox OS to Firefox OS).

Data to migrate:
- Contacts (CardDAV, VCF, Google, Facebook)
- SMS (see issue #21)
- Applications installed (check if there is a match of application)
- Applications credentials
- Search Engines
- Bookmarks
- Mail configuration
- Calendar configuration
- Wallpaper
- Ringtones
- Files (photos, music, videos, etc.)
- Alarms
- Language

**Comment by Amanjot1507** [comment]
Apart from the FirefoxOS version this app would have it's versions in Android, Windows, Iphone etc. so that it can be run on them, right ?

How will all this data be moved between the new device and the old one ?

**Comment by AntoineTurmel** [comment]
Yeah I think we need at least an app on Android/Windows Phone/iOS to export data.
Data could be export in several way:
- Source Phone storage and manual copy to the new Phone
- Wi-Fi (from a device to another)
- Bluetooth (from a device to another)
- Cloud (data need to be encrypted before on the Source Phone with a pass phrase)

**Comment by Amanjot1507** [comment]
Okay. I'm interested. I'll start working on it right away.

I have many questions, would love to have guidance from you. :)

**Comment by AntoineTurmel** [comment]
As of Android/Windows Phone/iOS, I don't have much knowledge but I can try to help you anyway.
For the project in general I'll do my best :)

**Comment by VenkatDatta** [comment]
I'm also interested in contributing to this project .
 @Amanjot1507 can we work on this as a team?

**Comment by Amanjot1507** [comment]
@VenkatDatta Sure!

**Comment by AntoineTurmel** [comment]
Closing it for now as Firefox OS is discontinued...
