### ISSUE TITLE
Blacklist number app

### ISSUE THREAD

**Issue by AntoineTurmel** [Mozilla-Student-Projects/Projects-Tracker#89]
Allow the user to blacklist a phone number.
This could be a dialer add-on starting with Firefox OS 2.5.

**Comment by sarkarshuvojit** [comment]
Hey? I'm interested to do this. This is still open right?

**Comment by AntoineTurmel** [comment]
Yeah, still opened. You might start looking at Firefox OS add-ons to do it:
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Add-ons

I'm not sure some stuff are possible though, like pretending line is busy or phone is off.
But it's possible to make the phone silent when some numbers calls.

**Comment by sarkarshuvojit** [comment]
So, I have to install a simulator(I don't own a FFOS device) > 2.5 right? The latest in the list is 2.6 
Also, should I im or irc you for further queries? or is github okay?

**Comment by Yoric** [comment]
Unfortunately, if my memory serves, you'll need a FFOS device to be able
to test incoming calls.

**Comment by sarkarshuvojit** [comment]
Oh yeah. Sorry. :disappointed: 
Should have thought about that.

**Comment by AntoineTurmel** [comment]
Closing it for now as Firefox OS is discontinued...
